// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGym.DAL;

#nullable disable

namespace QuanLyGym.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009150455_SeedAllTables")]
    partial class SeedAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "123456",
                            Role = "Admin",
                            Status = true,
                            Username = "admin"
                        },
                        new
                        {
                            AccountID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "123456",
                            Role = "PT",
                            Status = true,
                            Username = "pt_nam"
                        },
                        new
                        {
                            AccountID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "123456",
                            Role = "Member",
                            Status = true,
                            Username = "member_hung"
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchID = 1,
                            Address = "123 Cầu Giấy, Hà Nội",
                            BranchName = "QuanLyGym Cầu Giấy",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            Email = "caugiay@gym.com",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            Phone = "0987654321",
                            Status = true
                        },
                        new
                        {
                            BranchID = 2,
                            Address = "456 Xã Đàn, Hà Nội",
                            BranchName = "QuanLyGym Đống Đa",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            Email = "dongda@gym.com",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            Phone = "0912345678",
                            Status = true
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.CheckIn", b =>
                {
                    b.Property<int>("CheckInID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PTID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CheckInID");

                    b.HasIndex("BranchID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PTID");

                    b.ToTable("CheckIns");

                    b.HasData(
                        new
                        {
                            CheckInID = 1,
                            BranchID = 1,
                            CheckInTime = new DateTime(2026, 3, 1, 16, 55, 0, 0, DateTimeKind.Unspecified),
                            MemberID = 1,
                            Note = "Check-in tập cùng PT",
                            PTID = 1,
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.CheckInImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<int>("CheckInID")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationNote")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("CheckInID");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("CheckInImages");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            CheckInID = 1,
                            ImagePath = "uploads/checkin_001.jpg",
                            UploadedAt = new DateTime(2026, 3, 1, 16, 56, 0, 0, DateTimeKind.Unspecified),
                            VerificationNote = "Ảnh hợp lệ",
                            VerifiedBy = 1
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EquipmentID");

                    b.HasIndex("RoomID");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            EquipmentID = 1,
                            Description = "Máy chạy bộ cao cấp",
                            EquipmentCode = "CB-01",
                            EquipmentName = "Máy chạy bộ Technogym",
                            Price = 25000000m,
                            PurchaseDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomID = 2,
                            Status = "Tốt"
                        },
                        new
                        {
                            EquipmentID = 2,
                            Description = "Khung gánh tạ an toàn",
                            EquipmentCode = "SQ-01",
                            EquipmentName = "Dàn gánh tạ Squat Rack",
                            Price = 15000000m,
                            PurchaseDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomID = 1,
                            Status = "Tốt"
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.EquipmentMaintenance", b =>
                {
                    b.Property<int>("MaintenanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceID"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaintenanceID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("EquipmentMaintenances");

                    b.HasData(
                        new
                        {
                            MaintenanceID = 1,
                            Cost = 500000m,
                            Description = "Bảo dưỡng định kỳ thảm chạy và tra dầu",
                            EquipmentID = 1,
                            MaintenanceDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMaintenanceDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Hoàn thành"
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Incident", b =>
                {
                    b.Property<int>("IncidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IncidentID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("ReportedBy");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentID = 1,
                            Description = "Máy chạy bộ phát ra tiếng kêu lạ ở băng tải",
                            EquipmentID = 1,
                            Note = "Đã siết lại ốc và căn chỉnh băng tải",
                            ReportDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportedBy = 1,
                            ResolvedDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Resolved"
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BodyFat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MuscleMass")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MemberID");

                    b.HasIndex("AccountID");

                    b.HasIndex("BranchID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            AccountID = 3,
                            Address = "Cầu Giấy, Hà Nội",
                            Avatar = "",
                            BMI = 23m,
                            BodyFat = 18m,
                            BranchID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hung@gmail.com",
                            FullName = "Trần Văn Hùng",
                            Gender = "Nam",
                            Height = 172m,
                            MuscleMass = 32m,
                            Phone = "0977777777",
                            Weight = 68m
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Membership", b =>
                {
                    b.Property<int>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PackageID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsedSessions")
                        .HasColumnType("int");

                    b.HasKey("MembershipID");

                    b.HasIndex("BranchID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PackageID");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            MembershipID = 1,
                            BranchID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberID = 1,
                            PackageID = 2,
                            Price = 3000000m,
                            RegisterDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UsedSessions = 5
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.PT", b =>
                {
                    b.Property<int>("PTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PTID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PTID");

                    b.HasIndex("AccountID");

                    b.HasIndex("BranchID");

                    b.ToTable("PTs");

                    b.HasData(
                        new
                        {
                            PTID = 1,
                            AccountID = 2,
                            BranchID = 1,
                            DateOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nam@gym.com",
                            Experience = 5,
                            FullName = "Nguyễn Văn Nam",
                            Gender = "Nam",
                            Phone = "0988888888",
                            Specialization = "Tăng cơ, Giảm mỡ",
                            Status = true
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Package", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageID"));

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.HasKey("PackageID");

                    b.HasIndex("BranchID");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageID = 1,
                            Benefits = "Tập tự do các phòng",
                            BranchID = 1,
                            Description = "Gói cơ bản",
                            Duration = 30,
                            PackageName = "Gói Thường 1 Tháng",
                            Price = 500000m,
                            Status = true,
                            TotalSessions = 30
                        },
                        new
                        {
                            PackageID = 2,
                            Benefits = "Kèm PT 1-1, Nước uống miễn phí",
                            BranchID = 1,
                            Description = "Gói cao cấp",
                            Duration = 90,
                            PackageName = "Gói VIP 3 Tháng + PT",
                            Price = 3000000m,
                            Status = true,
                            TotalSessions = 36
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Progress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressID"));

                    b.Property<decimal>("Arm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BodyFat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Chest")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<decimal>("MuscleMass")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PTID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Thigh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProgressID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PTID");

                    b.ToTable("Progresses");

                    b.HasData(
                        new
                        {
                            ProgressID = 1,
                            Arm = 34m,
                            BMI = 23m,
                            BodyFat = 18m,
                            Chest = 95m,
                            Height = 172m,
                            Hip = 92m,
                            MemberID = 1,
                            MuscleMass = 32m,
                            Note = "Chỉ số ban đầu bình thường",
                            PTID = 1,
                            RecordDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thigh = 54m,
                            Waist = 78m,
                            Weight = 68m
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("RoomID");

                    b.HasIndex("BranchID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            BranchID = 1,
                            Capacity = 50,
                            Description = "Khu vực tập tạ tổng hợp",
                            RoomName = "Phòng Gym Tầng 1",
                            RoomType = "Gym",
                            Status = true
                        },
                        new
                        {
                            RoomID = 2,
                            BranchID = 1,
                            Capacity = 30,
                            Description = "Máy chạy bộ và xe đạp",
                            RoomName = "Phòng Cardio Tầng 2",
                            RoomType = "Cardio",
                            Status = true
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PTID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ScheduleID");

                    b.HasIndex("BranchID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PTID");

                    b.HasIndex("RoomID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            BranchID = 1,
                            EndTime = new TimeSpan(0, 18, 30, 0, 0),
                            MemberID = 1,
                            Note = "Hội viên tập tốt, nâng tạ ngực 50kg",
                            PTID = 1,
                            RoomID = 1,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0),
                            Status = "Completed",
                            TrainingDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingType = "Tập Ngực & Tay Sau"
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.WorkingSchedule", b =>
                {
                    b.Property<int>("WorkingScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkingScheduleID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PTID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkingScheduleID");

                    b.HasIndex("BranchID");

                    b.HasIndex("PTID");

                    b.ToTable("WorkingSchedules");

                    b.HasData(
                        new
                        {
                            WorkingScheduleID = 1,
                            BranchID = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            PTID = 1,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Status = "Đã ca",
                            WorkDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.CheckIn", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.HasOne("QuanLyGym.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Member");

                    b.Navigation("PT");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.CheckInImage", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.CheckIn", "CheckIn")
                        .WithMany()
                        .HasForeignKey("CheckInID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.PT", "VerifiedByPT")
                        .WithMany()
                        .HasForeignKey("VerifiedBy");

                    b.Navigation("CheckIn");

                    b.Navigation("VerifiedByPT");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Equipment", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.EquipmentMaintenance", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Incident", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Member", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.Navigation("Account");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Membership", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.HasOne("QuanLyGym.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Member");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.PT", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.Navigation("Account");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Package", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Progress", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("PT");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Room", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.Schedule", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.HasOne("QuanLyGym.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGym.DAL.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Member");

                    b.Navigation("PT");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyGym.DAL.Entities.WorkingSchedule", b =>
                {
                    b.HasOne("QuanLyGym.DAL.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID");

                    b.HasOne("QuanLyGym.DAL.Entities.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("PT");
                });
#pragma warning restore 612, 618
        }
    }
}
